application: tac-toe
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: chatactoe.app
  
libraries:
- name: django
  version: "1.4"
- name: jinja2
  version: 2.6
